syntax on
set nocompatible
set number
set nowrap
set noshowmode
set expandtab
set list
set listchars=trail:·,tab:▸\
set bg=dark
set colorcolumn=80

let g:ctrlp_user_command = ['.git/', 'git --git-dir=%s/.git ls-files -oc --exclude-standard']

filetype plugin indent on

autocmd FileType yaml setlocal shiftwidth=2 tabstop=2
autocmd FileType json setlocal shiftwidth=2 tabstop=2
autocmd FileType javascript setlocal shiftwidth=2 tabstop=2

map <C-n> :NERDTreeToggle<CR>
